fix: dependency error
https://github.com/googleapis/google-api-python-client/issues/1579

There's been some releases in pyparsing, which broke httplib2, which broke google-api-python-client, which is used by intraday CF - which broke intraday CF deployment

AttributeError: module 'pyparsing' has no attribute 'downcaseTokens'